<a href="https://colab.research.google.com/github/Yassineabdelhedi379/CP0/blob/main/Arrays_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)


Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Convert the said array to an ordinary list with the same items:
[1, 3, 5, 3, 7, 1, 9, 3]


In [2]:

import numpy as np
  

n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])

print("Numpy Matrix is:")
print(n_array)
  
trace = np.trace(n_array)
  
  
print("\nTrace of given 3X3 matrix:")
print(trace)

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Trace of given 3X3 matrix:
176


In [6]:
import numpy as np
x = np.array([[0, 4, 5], [1, 2, 3]])
print("Original array: ")
print(x)
print("Values bigger than 3 =", x[x>3])
print("Their indices are ", np.nonzero(x > 3))

Original array: 
[[0 4 5]
 [1 2 3]]
Values bigger than 3 = [4 5]
Their indices are  (array([0, 0]), array([1, 2]))


In [9]:

def getSum(X):
    sum=0
    for i in X:
        sum+=i
    return sum
 

def findSwapValues(A,B):
   
    sum1=getSum(A)
    sum2=getSum(B)

    k=False
 
   
    val1,val2=0,0
    for i in A:
        for j in B:
            newsum1=sum1-i+j
            newsum2=sum2-j+i
             
            if newsum1 ==newsum2:
                val1=i
                val2=j
               
                k=True
                break
     
        if k==True:
            break
    print(val1,val2)
    return
 
 

A=[4,1,2,1,1,2]
B=[3,6,3,3]
 

findSwapValues(A,B)
 


4 6


In [16]:
import numpy as np 
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b 
a + 5
c = np.ones((3, 3))
c
c + a 
a = np.arange(3)
b = np.arange(3) [:, np.newaxis]

print(a)
print(b)
a + b

[0 1 2]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [20]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.756871   0.96480671 0.34664512 0.12438467 0.26685686 0.91858805
  0.7452721  0.26861586 0.25365951 0.34969789]
 [0.76272765 0.78639145 0.73054821 0.04448631 0.90536709 0.27026937
  0.93486028 0.55371534 0.07117372 0.10434615]
 [0.81601199 0.47250197 0.02242087 0.46088339 0.36256493 0.32283405
  0.17850158 0.92251755 0.97653168 0.40471685]
 [0.81479154 0.23479562 0.0352711  0.66689945 0.73340323 0.95078065
  0.81704478 0.91213101 0.82795085 0.94089468]
 [0.07795377 0.41209157 0.70396574 0.7150355  0.24843774 0.45363371
  0.61971846 0.86522039 0.22065562 0.97787917]]

Subtract the mean of each row of the said matrix:

[[ 0.25733123  0.46526693 -0.15289466 -0.37515511 -0.23268292  0.41904827
   0.24573232 -0.23092392 -0.24588027 -0.14984188]
 [ 0.24633909  0.27000289  0.21415965 -0.47190225  0.38897853 -0.24611919
   0.41847172  0.03732678 -0.44521483 -0.4120424 ]
 [ 0.32206351 -0.02144651 -0.47152762 -0.03306509 -0.13138355 -0.17111444
  -0.31544691  0.42856906  0.4